### ISSUE TITLE
Nothing happens in localhost server

### ISSUE THREAD

**Issue by KimiaaSrh** [leftthomas/CapsNet#3]
sorry to say that (maybe it's my fault) , my problem is that nothing happens in visdom enviroment here : http://127.0.0.1:8097/ .
I don't know maybe some time I should wait to get the result .

![Capture](https://user-images.githubusercontent.com/51259793/107327920-2a8d4380-6ac3-11eb-856f-357c3b25b1c0.JPG)

**Comment by leftthomas** [comment]
@accioCodes you could go to the `visdom` website to see how to config that.
